# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppCenterTest' do
  pod 'AppCenter/Crashes', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.10.0'
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppCenterTest

  platform :ios, '9.0'
  pod 'react-native-config', :path => '../node_modules/react-native-config'

end
